name: Arafat Web APK Engine

on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android Package
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "${{ github.event.client_payload.app_name }}" "${{ github.event.client_payload.package_name }}" --web-dir dist
          mkdir dist
          echo '${{ github.event.client_payload.html_code }}' > dist/index.html
          npx cap add android
          npx cap sync android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.app_name }}-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
